spring:
  application:
    name: api-java
    jackson:
      default-property-inclusion: non_null
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  dynamodb:
    table-name: ${DYNAMO_USER_TABLE}



appDescripcion: Api para crear usuarios con sus respectivos roles
appVersion: 1.0.0